Algoritmo "Entrada de dados"

Var

 idade : inteiro
 nome : caractere
 salario1, salario2 : real
 
Inicio
 escreva("Digite seu nome: ")
 leia(nome)
 escreva("Digite sua idade: ")
 leia(idade)
 escreval("Digite quanto você ganhou nos ultimos 2 meses:")
 leia(salario1)
 leia(salario2)
 
 escreval()
 escreval("DADOS DIGITADOS:")
 escreval("Nome: ", nome)
 escreval("Idade: ", idade)
 Escreval("Salario 1: ", salario1:1:2)
 Escreval("Salerio 2: ", salario2:1:2)


Fimalgoritmo